# Generated by Django 3.2.6 on 2022-01-06 01:19

import accounts.queries
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=models.SET(accounts.queries.get_deleted_user), related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('down_votes', models.ManyToManyField(related_name='comment_down_votes', to=settings.AUTH_USER_MODEL, verbose_name='up vote')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='parent comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='post')),
                ('up_votes', models.ManyToManyField(related_name='comment_up_votes', to=settings.AUTH_USER_MODEL, verbose_name='up vote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
